version: '3.7'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./packages/client
  #     target: client-dev
  #   env_file:
  #     - .env
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - prix-tour-db
  #   environment:
  #     WAIT_HOSTS: backend:3000
  #     VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
  #   volumes:
  #     - /usr/src/app/node_modules

  backend:
    container_name: backend
    build:
      context: ./packages/server
      target: server-dev
    env_file:
      - .env
    ports:
      - '3000:${PORT}'
    depends_on:
      - prix-tour-db
    environment:
      WAIT_HOSTS: prix-tour-db:${DATABASE_PORT}
    volumes:
      - .:/usr/src/app

  prix-tour-db:
    container_name: prix-tour-db
    restart: always
    image: postgis/postgis
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:${DATABASE_PORT}'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
