version: '3.7'

services:    
  frontend:
    container_name: frontend
    build:
      context: ./packages/client
      target: client-dev
    ports:
      - 5173:5173
    depends_on:
      - prix-tour-db
    environment:
      WAIT_HOSTS: backend:3000
      VITE_GOOGLE_API_KEY: AIzaSyCWy5qfDDQz8qFhdVX5IkNEP_8e95roVUs
    volumes:
      - /usr/src/app/node_modules
      
  backend:
    container_name: backend
    build: 
      context: ./packages/server
      target: server-dev 
    ports:
      - '3000:3000'
    depends_on:
      - prix-tour-db
    environment:
      WAIT_HOSTS: prix-tour-db:5432
    volumes:
      - .:/usr/src/app

  prix-tour-db:
    container_name: prix-tour-db
    restart: always
    image: postgis/postgis
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: prix-tour-db
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  
