name: Build

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          cache: 'yarn'

      - name: Install modules
        run: yarn workspace server install --frozen-lockfile
      
      - name: Running tests
        run: yarn workspace server test:unit
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [unit-tests]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: DockerHub login
        run: docker login -u wagnernasc -p ${{ secrets.DOCKERHUB_KEY }}

      - name: Build image
        run: docker build . -f ./packages/server/Dockerfile.build -t wagnernasc/prix-tour:latest
      
      - name: Sending image
        run: docker push wagnernasc/prix-tour:latest


      
  