name: Sonarqube Frontend

on:
  pull_request:
    paths:
      - 'packages/client/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  sonarcloud-frontend:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}