name: Sonarqube Backend

on:
  push:
    paths:
      - 'packages/server/**'
      - '.github/workflows/**'
    branches:
      - main

  pull_request:
    paths:
      - 'packages/server/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  sonarcloud-backend:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}